#ANTES DE CREAR LA BD ME ASEGURO DE ELIMINARLA SI ES QUE EXISTE
DROP DATABASE IF EXISTS ejercicio2;
CREATE DATABASE ejercicio2;

#INDICO QUE QUIERO USAR LA BD RECIÉN CREADA
USE ejercicio2;

#LA TABLA MEMEBERS PUEDO CREARLA PRIMERO PORQUE NO RECIBE NINGUNA FK
CREATE TABLE miembros(
	id SMALLINT auto_increment NOT NULL,
    name VARCHAR(30) NOT NULL,
    email VARCHAR(25) NOT NULL,
	telefono CHAR(11) NOT NULL,
    CONSTRAINT id PRIMARY KEY (id)
);

